### ISSUE TITLE
Node-Mapnik那篇文章，不用在单独安装mapnik吗？

### ISSUE THREAD

**Issue by yh371174229** [ConorPai/ConorPai.github.io#39]
Node-Mapnik那篇文章，不用在单独安装mapnik吗？
我按照您的步骤node-mapnik部署成功了，但是我有个疑问，mapnik那步不用部署吗

**Comment by ConorPai** [comment]
@yh371174229 不用，node-mapnik里面有源码，会编译一套库调用

**Comment by yh371174229** [comment]
测试了，在aws直接安装你文章的步骤安装，可以允许。不用再单独安装mapnik了。非常感谢
